### ISSUE TITLE
Demo app on Glitch is unavailable

### ISSUE THREAD

**Issue by laudenberg** [hotwired/turbo-native-demo#8]
The demo app https://turbo-native-demo.glitch.me/ on Glitch is currently unavailable and responds with a _504 Gateway Time-out_ error if at all.

**Comment by jayohms** [comment]
If you see this again, please let me know 👍

**Comment by fahadmu** [comment]
"Oops! This project isn't running"
https://turbo-native-demo.glitch.me/
